/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vectoresYMatrices;

import javax.swing.DefaultListModel;

/**
 *
 * @author Usuario
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        texto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        lista = new javax.swing.JList<>();
        label = new javax.swing.JLabel();
        vector = new javax.swing.JButton();
        matris = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        texto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoActionPerformed(evt);
            }
        });
        jPanel1.add(texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 180, 190, 40));

        lista.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jScrollPane1.setViewportView(lista);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 30, 110, 130));

        label.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        jPanel1.add(label, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 370, 170));

        vector.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        vector.setText("Mi boton tipo vector");
        vector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vectorActionPerformed(evt);
            }
        });
        jPanel1.add(vector, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 150, -1));

        matris.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        matris.setText("Matriz");
        matris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matrisActionPerformed(evt);
            }
        });
        jPanel1.add(matris, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jButton3.setText("Borrar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, -1, -1));

        jButton1.setText("Recuperar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 405, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoActionPerformed
    private int contadorNombres = 0;
    private int num = 0;
    private void vectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vectorActionPerformed
        String nombreObtenido = texto.getText();
        String[] nombres = new String[50];
        num++;
        nombres[contadorNombres] = nombreObtenido;
        contadorNombres++;
        String contenidoCompleto="";
        for(String nombresSeparados : nombres){
            if(nombresSeparados != null){
                contenidoCompleto =  
                        label.getText() 
                        + "<html><alig>" 
                        + num 
                        + "." 
                        +  nombresSeparados 
                        + ", ";
                label.setText(contenidoCompleto);
                lista.removeAll();
            }
        }
    }//GEN-LAST:event_vectorActionPerformed
    private final DefaultListModel modelo = new DefaultListModel();
    private void matrisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matrisActionPerformed
        String[][] matriz = new String[5][5];
        modelo.clear();
        lista.setModel(modelo);
        for(int i = 0;i<5;i++)
        {
            for(int j = 0;j<5;j++)
            {
                String mostrar = texto.getText()+"["+i+"]"+"["+j+"]";
                matriz[i][j] = mostrar;
                modelo.addElement(mostrar);
                //JOptionPane.showMessageDialog(null, mostrar);
            }
        }
    }//GEN-LAST:event_matrisActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        label.setText("");
        texto.setText("");
        
        contadorNombres = 0;
        
        modelo.removeAllElements();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         int e = modelo.getSize();
         String recuperar = "";
        
         for(int i = 0; i<e; i++)
         {
        Object copiar = "<html><alig>" + modelo.getElementAt(i) +", ";
             recuperar += copiar;
         }
         label.setText(recuperar);
    }//GEN-LAST:event_jButton1ActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label;
    private javax.swing.JList<String> lista;
    private javax.swing.JButton matris;
    private javax.swing.JTextField texto;
    private javax.swing.JButton vector;
    // End of variables declaration//GEN-END:variables
}
